name: Deploy Web App to Shared ECR 

on:
  workflow_call:
    inputs:
      # pass in environment through manual trigger, if not passed in, default to 'dev'
      env:
        required: true
        type: string
        default: 'dev'
      url:
        required: true
        type: string
        default: ''
      ecr:
        required: true
        type: string
        default: ''
      aws_region:
        required: true
        type: string
        default: ''  
      # working-directory is added to accommodate monorepo.  For multi repo, defaults to '.', current directory
      working-directory:
        required: false
        type: string
        default: '.'
                
jobs:

  deploy-develop:
    name: Deploy Dev
    runs-on: ubuntu-latest
    # needs: [build]
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/develop'
    environment:
      name: dev
      url: ${{ inputs.url }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Delta Shared AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: OIDCSession

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-node-modules
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashfiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Login AWS ECR
        id: login-ecr-private
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Source-${{ steps.gitversion.outputs.semVer }}
          path: Source

      - name: Install dependencies
        working-directory: Source
        run: npm ci --legacy-peer-deps

      - name: Build
        working-directory: Source
        run: npm run build

      - name: Docker build, tag and push docker image to Amazon ECR Private
        working-directory: Source
        env:
          REGISTRY: ${{ steps.login-ecr-private.outputs.registry }}
          REPOSITORY: ${{ inputs.ecr }}
          SEMVER: ${{ steps.gitversion.outputs.semVer }}
        run: |
          echo SemVer: $SEMVER
          docker build -t $REGISTRY/$REPOSITORY:$SEMVER .
          docker push $REGISTRY/$REPOSITORY:$SEMVER
          
  deploy-stable:
    name: Deploy Stable
    runs-on: ubuntu-latest
    # needs: [build]
    if: |
      github.event_name != 'pull_request' && 
      (
        startsWith(github.ref,'refs/heads/release/') ||
        startsWith(github.ref,'refs/heads/fix/')
      )
    environment:
      name: stable
      url: ${{ inputs.url }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Configure Delta Shared AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: af-south-1
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: OIDCSession

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-node-modules
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashfiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Login AWS ECR
        id: login-ecr-private
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Source-${{ steps.gitversion.outputs.semVer }}
          path: Source

      - name: Install dependencies
        working-directory: Source
        run: npm ci --legacy-peer-deps  
        
      - name: Build
        working-directory: Source
        run: npm run build

      - name: Docker build, tag and push docker image to Amazon ECR Private
        working-directory: Source
        env:
          REGISTRY: ${{ steps.login-ecr-private.outputs.registry }}
          REPOSITORY: ${{ inputs.ecr }}
          SEMVER: ${{ steps.gitversion.outputs.semVer }}
        run: |
          echo SemVer: $SEMVER
          docker build -t $REGISTRY/$REPOSITORY:$SEMVER .
          docker push $REGISTRY/$REPOSITORY:$SEMVER    
